version: '3'
services:
  app:
    image: spring-boot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Ambiente por defecto
    volumes:
      - ./logs:/app/logs  # Monta logs locales (opcional)